// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using BarkerSharper.Model;
//
//    var barkNotificationResponseModel = BarkNotificationResponseModel.FromJson(jsonString);

namespace BarkerSharper.Model
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class BarkNotificationResponseModel
    {
        [JsonProperty("code")]
        public long Code { get; set; }

        [JsonProperty("message")]
        public string Message { get; set; }

        [JsonProperty("timestamp")]
        public long Timestamp { get; set; }
    }

    public partial class BarkNotificationResponseModel
    {
        public static BarkNotificationResponseModel FromJson(string json) => JsonConvert.DeserializeObject<BarkNotificationResponseModel>(json, BarkerSharper.Model.BarkNotificationResponseModelConverter.Settings);
    }

    internal static class BarkNotificationResponseModelConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}